<?php

namespace Database\Seeders;

use App\Models\Student;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            [
                'nis' => 'SJI-2026-001',
                'name' => 'Rian Hidayat',
                'japanese_name' => 'リアン・ヒダヤット',
                'nik' => '3201123456780001',
                'phone' => '081234567891',
                'email' => 'rian.hidayat@gmail.com',
                'gender' => 'Laki-laki',
                'birth_place' => 'Bandung',
                'birth_date' => '2001-05-14',
                'education' => 'SMK Teknik Mesin',
                'address' => 'Jl. Cibaduyut No. 45, RT 02/05',
                'city' => 'Bandung',
                'emergency_contact_name' => 'Ahmad (Ayah)',
                'emergency_contact_phone' => '081298765431',
                'batch' => 'Angkatan 40 - Tokutei Ginou SSW',
                'program' => 'Tokutei Ginou (SSW)',
                'sector' => 'Pengolahan Makanan (Food Processing)',
                'entry_date' => '2025-11-01',
                'departure_date' => '2026-05-15',
                'destination_company' => 'Nichirei Foods Inc.',
                'destination_prefecture' => 'Chiba',
                'status' => 'departed',
                'japanese_level' => 'JLPT N4 & JFT-Basic A2',
                'ssw_certificate' => 'Sertifikat SSW Pengolahan Makanan (Lulus)',
                'passport_number' => 'C1234567',
                'passport_expiry' => '2036-02-10',
                'total_cost' => 28000000,
                'paid_amount' => 28000000,
                'payment_scheme' => 'mandiri',
                'payment_status' => 'paid',
                'payment_notes' => 'Pembayaran lunas sebelum keberangkatan.',
                'photo' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
                'admin_notes' => 'Siswa teladan, telah resmi bekerja di Prefektur Chiba.',
            ],
            [
                'nis' => 'SJI-2026-002',
                'name' => 'Siti Nurhaliza',
                'japanese_name' => 'シティ・ヌルハリザ',
                'nik' => '3273123456780002',
                'phone' => '081398765432',
                'email' => 'siti.nurhaliza@gmail.com',
                'gender' => 'Perempuan',
                'birth_place' => 'Semarang',
                'birth_date' => '2002-08-20',
                'education' => 'D3 Keperawatan',
                'address' => 'Jl. Pandanaran No. 12',
                'city' => 'Semarang',
                'emergency_contact_name' => 'Suryo (Ayah)',
                'emergency_contact_phone' => '081345678901',
                'batch' => 'Angkatan 41 - Tokutei Ginou Kaigo',
                'program' => 'Tokutei Ginou (SSW)',
                'sector' => 'Perawat Lansia (Kaigo / Caregiver)',
                'entry_date' => '2026-01-10',
                'departure_date' => '2026-08-20',
                'destination_company' => 'Aoyama Medical Group',
                'destination_prefecture' => 'Tokyo',
                'status' => 'passed_interview',
                'japanese_level' => 'JLPT N4 (Score: 125)',
                'ssw_certificate' => 'Sertifikat SSW Careworker (Lulus)',
                'passport_number' => 'C2345678',
                'passport_expiry' => '2036-04-15',
                'total_cost' => 32000000,
                'paid_amount' => 22000000,
                'payment_scheme' => 'talangan',
                'payment_status' => 'partial',
                'payment_notes' => 'DP 22 Juta terbayar, sisa 10 Juta via skema dana talangan cicil di Jepang.',
                'photo' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
                'admin_notes' => 'Lolos wawancara user Tokyo, saat ini proses pengurusan CoE di Imigrasi Jepang.',
            ],
            [
                'nis' => 'SJI-2026-003',
                'name' => 'Bagus Pratama',
                'japanese_name' => 'バグス・プラタマ',
                'nik' => '3301123456780003',
                'phone' => '081277665544',
                'email' => 'bagus.pratama@gmail.com',
                'gender' => 'Laki-laki',
                'birth_place' => 'Cilacap',
                'birth_date' => '2003-03-12',
                'education' => 'SMK Otomotif',
                'address' => 'Jl. Gatot Subroto No. 89',
                'city' => 'Cilacap',
                'emergency_contact_name' => 'Supri (Paman)',
                'emergency_contact_phone' => '081233445566',
                'batch' => 'Angkatan 42 - Magang Manufaktur',
                'program' => 'Ginou Jisshusei (Magang)',
                'sector' => 'Manufaktur & Pengelasan (Welding)',
                'entry_date' => '2026-03-01',
                'departure_date' => null,
                'destination_company' => 'Denso Corporation Associate',
                'destination_prefecture' => 'Aichi',
                'status' => 'active',
                'japanese_level' => 'N5 (Persiapan N4)',
                'ssw_certificate' => '-',
                'passport_number' => 'C3456789',
                'passport_expiry' => '2036-05-10',
                'total_cost' => 25000000,
                'paid_amount' => 10000000,
                'payment_scheme' => 'mandiri',
                'payment_status' => 'partial',
                'payment_notes' => 'Pembayaran Termin 1 sebesar 10 Juta sudah masuk.',
                'photo' => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
                'admin_notes' => 'Siswa rajin, target ujian JFT bulan depan.',
            ],
            [
                'nis' => 'SJI-2026-004',
                'name' => 'Dewi Lestari',
                'japanese_name' => 'デウィ・レスタリ',
                'nik' => '3501123456780004',
                'phone' => '081388990011',
                'email' => 'dewi.lestari@gmail.com',
                'gender' => 'Perempuan',
                'birth_place' => 'Malang',
                'birth_date' => '2000-11-25',
                'education' => 'S1 Sastra Jepang',
                'address' => 'Jl. Ijen No. 102',
                'city' => 'Malang',
                'emergency_contact_name' => 'Hartono (Ayah)',
                'emergency_contact_phone' => '081399887766',
                'batch' => 'Angkatan 42 - Tokutei Ginou SSW',
                'program' => 'Engineer & Profesional',
                'sector' => 'Penerjemah & Admin Kantor (Tsuyaku)',
                'entry_date' => '2026-04-15',
                'departure_date' => null,
                'destination_company' => 'Kyoto Hospitality Group',
                'destination_prefecture' => 'Kyoto',
                'status' => 'interview',
                'japanese_level' => 'JLPT N2 (Lulus)',
                'ssw_certificate' => 'Sertifikat JFT Business N2',
                'passport_number' => 'C4567890',
                'passport_expiry' => '2036-06-01',
                'total_cost' => 20000000,
                'paid_amount' => 0,
                'payment_scheme' => 'mandiri',
                'payment_status' => 'unpaid',
                'payment_notes' => 'Menunggu verifikasi pembayaran tahap registrasi awal.',
                'photo' => 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
                'admin_notes' => 'Bahasa Jepang sangat fasih, sedang penjadwalan interview user Kyoto.',
            ]
        ];

        foreach ($students as $data) {
            Student::updateOrCreate(
                ['nis' => $data['nis']],
                $data
            );
        }
    }
}
